export const CLICK_START = 'GRTHProject/AttendanceRegistration/CLICK_START';
// GET CURRENT TODAY ATTENDANCE
export const GET_CURRENT_TODAY_ATTENDANCE_OF_USER = 'GRTHProject/AttendanceRegistration/GET_CURRENT_TODAY_ATTENDANCE_OF_USER';
export const GET_CURRENT_TODAY_ATTENDANCE_OF_USER_SUCCESS = 'GRTHProject/AttendanceRegistration/GET_CURRENT_TODAY_ATTENDANCE_OF_USER_SUCCESS';
export const GET_CURRENT_TODAY_ATTENDANCE_OF_USER_ERROR = 'GRTHProject/AttendanceRegistration/GET_CURRENT_TODAY_ATTENDANCE_OF_USER_ERROR';
// UPDATE ATTENDANCE
export const UPDATE_ATTENDANCE = 'GRTHProject/AttendanceRegistration/UPDATE_ATTENDANCE';
// export const UPDATE_ATTENDANCE_SUCCESS = 'GRTHProject/AttendanceRegistration/UPDATE_ATTENDANCE_SUCCESS';
// export const UPDATE_ATTENDANCE_ERROR = 'GRTHProject/AttendanceRegistration/UPDATE_ATTENDANCE_ERROR';

// ADD ATTENDANCE
export const ADD_ATTENDANCE = 'GRTHProject/AttendanceRegistration/ADD_ATTENDANCE';
// export const ADD_ATTENDANCE_SUCCESS = 'GRTHProject/AttendanceRegistration/ADD_ATTENDANCE_SUCCESS';
// export const ADD_ATTENDANCE_ERROR = 'GRTHProject/AttendanceRegistration/ADD_ATTENDANCE_ERROR';