// GET CURRENT TODAY ATTENDANCE
export const GET_CURRENT_TODAY_ATTENDANCE_OF_USER = 'GRTHProject/AttendanceRegistration/GET_CURRENT_TODAY_ATTENDANCE_OF_USER';
export const GET_CURRENT_TODAY_ATTENDANCE_OF_USER_SUCCESS = 'GRTHProject/AttendanceRegistration/GET_CURRENT_TODAY_ATTENDANCE_OF_USER_SUCCESS';
export const GET_CURRENT_TODAY_ATTENDANCE_OF_USER_ERROR = 'GRTHProject/AttendanceRegistration/GET_CURRENT_TODAY_ATTENDANCE_OF_USER_ERROR';
// UPDATE ATTENDANCE
export const UPDATE_ATTENDANCE = 'GRTHProject/AttendanceRegistration/UPDATE_ATTENDANCE';

// ADD ATTENDANCE
export const ADD_ATTENDANCE = 'GRTHProject/AttendanceRegistration/ADD_ATTENDANCE';