// UPDATE ATTENDANCE
export const UPDATE_ATTENDANCE = 'GRTHProject/App/UPDATE_ATTENDANCE';
export const UPDATE_ATTENDANCE_SUCCESS = 'GRTHProject/App/UPDATE_ATTENDANCE_SUCCESS';
export const UPDATE_ATTENDANCE_ERROR = 'GRTHProject/App/UPDATE_ATTENDANCE_ERROR';

// ADD ATTENDANCE
export const ADD_ATTENDANCE = 'GRTHProject/App/ADD_ATTENDANCE';
export const ADD_ATTENDANCE_SUCCESS = 'GRTHProject/App/ADD_ATTENDANCE_SUCCESS';
export const ADD_ATTENDANCE_ERROR = 'GRTHProject/App/ADD_ATTENDANCE_ERROR';


// Login
export const LOGIN_LOADED = 'GRTHProject/APP/LOGIN_LOADED';
export const LOGIN_LOADED_SUCCESS = 'GRTHProject/APP/LOGIN_LOADED_SUCCESS';
export const LOGIN_LOADED_ERROR = 'GRTHProject/APP/LOGIN_LOADED_ERROR';

// Logout
export const LOGOUT = 'GRTHProject/APP/RESET_NAME_PASSWORD';
